imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: applications_connectors.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine_mongodb:
    connections:
        default:
            server: "mongodb://%database_host%:%database_port%"
            options: {}
    default_database: "%database_name%"
    document_managers:
        default:
            auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

hautelook_alice:
    db_drivers:
        orm: false
        mongodb: true
    locale: fr_FR
    seed: 1
    persist_once: false
    loading_limit: 5

csa_guzzle:
    profiler: %kernel.debug%
    logger: true
    clients:
        runtastic:
            lazy: true
            config:
                base_uri: https://www.runtastic.com
        runkeeper:
            lazy: true
            config:
                base_uri: https://api.runkeeper.com
        endomondo:
            lazy: true
            config:
                base_uri: https://api.mobile.endomondo.com/mobile
        nike_plus:
            lazy: true
            config:
                base_uri: https://api.nike.com/v1/me
        strava:
            lazy: true
            config:
                base_uri: https://www.strava.com/api/v3

jms_serializer:
    metadata:
        auto_detection: true
        directories:
            AppBundle:
                namespace_prefix: 'AppBundle'
                path: '%kernel.root_dir%/config/bundles/jms_serializer'
            FOSUserBundle:
                namespace_prefix: 'FOS\UserBundle'
                path: '%kernel.root_dir%/config/bundles/jms_serializer'

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    # disable_csrf_role: ROLE_API
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json

lexik_jwt_authentication:
    private_key_path: %jwt_private_key_path%
    public_key_path:  %jwt_public_key_path%
    pass_phrase:      %jwt_key_pass_phrase%
    token_ttl:        %jwt_token_ttl%
