challengeme_oauth:
    type: annotation
    resource: "@AppBundle/Controller/OAuthController.php"

challengeme_api:
    type: rest
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /api

api_login_check:
    path: /jwt/login_check
