security:
    encoders:
        AppBundle\Document\User:
            algorithm: bcrypt

    providers:
        mongo_provider:
            mongodb:
                class: 'AppBundle\Document\User'
                property: username

    firewalls:
        login:
            pattern: ^/jwt/login
            provider: mongo_provider
            stateless: true
            anonymous: true
            form_login:
                check_path:               /jwt/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/jwt
            provider: mongo_provider
            stateless: true
            lexik_jwt: ~

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout: ~
            provider: mongo_provider

    access_control:
        - { path: ^/jwt/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/jwt,       roles: IS_AUTHENTICATED_FULLY }
