services:
    faker.provider.password:
        class: 'AppBundle\DataFixtures\Provider\PasswordProvider'
        arguments: ['@security.password_encoder']
        tags: [{ name: hautelook_alice.faker.provider }]

    app.token_authenticator:
        class: 'AppBundle\Security\TokenAuthenticator'
        arguments: ['@router']

    app.application.manager:
        class: 'AppBundle\Manager\ApplicationManager'
        arguments: ['@service_container']
